edition = "2024"

# --- Cleanups ---
merge_derives = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true

# --- Formatting Style ---
max_width = 100
chain_width = 80
fn_call_width = 80
struct_lit_width = 50
array_width = 60
single_line_if_else_max_width = 50
use_small_heuristics = "Max"

# --- Consistency ---
newline_style = "Unix"
